spring.application.name=stop-service
server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/stop_db
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.path=/swagger-ui.html

app.security.jwt.secret=Y2FtcHVzLWJ1cy1iYWNrZW5kLXNlY3VyaXR5LWtleS0yMDI2LXNlY3JldA==
app.security.jwt.expiration-ms=86400000
